services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - kubo
      - leanish
      - send
    env_file:
      - path: .env.caddy
        required: true
      - path: .env.caddy.local
        required: false
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy

  kubo:
    container_name: kubo
    hostname: helion
    image: ipfs/kubo
    ports:
      - 127.0.0.1:5001:5001
      - 4001:4001/tcp
      - 4001:4001/udp
      - 8080:8080
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  leanish:
    container_name: leanish
    image: natoboram/leanish
    ports:
      - 3000:3000
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - send-redis:/data

  send:
    container_name: send
    depends_on:
      - redis
    environment:
      - BASE_URL=https://send.natoboram.duckdns.org
      - REDIS_HOST=redis
    image: registry.gitlab.com/timvisee/send
    ports:
      - 1443:1443
    restart: always

  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

volumes:
  send-redis:
