include:
  - path: authentik.compose.yaml
  - path: caddy.compose.yaml
  - path: glances.compose.yaml
  - path: jellyfin.compose.yaml
  - path: kubo.compose.yaml
  - path: leanish.compose.yaml
  - path: metube.compose.yaml
  - path: myspeed.compose.yaml
  - path: nextcloud.compose.yaml
  - path: ollama.compose.yaml
  - path: planka.compose.yaml
  - path: qbittorrent.compose.yaml
  - path: send.compose.yaml
  - path: syncthing.compose.yaml
  - path: tandoor.compose.yaml
  - path: uptime-kuma.compose.yaml
  #- path: ocis.compose.yaml

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
