include:
  - path: nextcloud.compose.yaml
  - path: send.compose.yaml

networks:
  caddy:
    enable_ipv6: true
  caddy-collabora:
  caddy-glances:
  caddy-kubo:
  caddy-leanish:
  caddy-nextcloud:
  grafana-victoria-metrics:
  vmagent-caddy:
  vmagent-collabora:
  vmagent-victoria-metrics:

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - glances
      - kubo
      - leanish
      - nextcloud
      - send
    env_file:
      - path: .env.caddy
      - path: .env.caddy.local
    networks:
      - caddy
      - caddy-collabora
      - caddy-glances
      - caddy-kubo
      - caddy-leanish
      - caddy-nextcloud
      - caddy-send
      - vmagent-caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    user: 1000:1000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/log/caddy:/var/log/caddy
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy
      - nextcloud:/var/www/nextcloud:ro

  glances:
    container_name: glances
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: all
              driver: nvidia
    env_file:
      - path: .env.glances
      - path: .env.glances.local
    image: nicolargo/glances:latest-full
    networks:
      - caddy-glances
    restart: always
    volumes:
      - ./glances:/root/.config/glances:ro
      - /etc/os-release:/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - victoria-metrics
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - grafana-victoria-metrics
    restart: always

  kubo:
    container_name: kubo
    hostname: helion
    image: ipfs/kubo
    networks:
      - caddy-kubo
    ports:
      - 127.0.0.1:5001:5001
      - 4001:4001/tcp
      - 4001:4001/udp
      - 8080:8080
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  leanish:
    container_name: leanish
    image: natoboram/leanish
    networks:
      - caddy-leanish
    restart: always

  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

  vmagent:
    command:
      - --promscrape.config=/etc/prometheus/prometheus.yaml
      - --remoteWrite.url=http://victoria-metrics:8428/api/v1/write
    container_name: vmagent
    depends_on:
      - caddy
      - collabora
      - victoria-metrics
    env_file:
      - path: .env.vmagent
      - path: .env.vmagent.local
    networks:
      - vmagent-caddy
      - vmagent-collabora
      - vmagent-victoria-metrics
    image: victoriametrics/vmagent
    restart: always
    volumes:
      - vmagent:/vmagentdata
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics
    networks:
      - grafana-victoria-metrics
      - vmagent-victoria-metrics
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    restart: always
    volumes:
      - victoria-metrics:/storage

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  grafana:
  victoria-metrics:
  vmagent:
