include:
  - path: glances.compose.yaml
  - path: kubo.compose.yaml
  - path: nextcloud.compose.yaml
  - path: ollama.compose.yaml
  - path: send.compose.yaml
  - path: tandoor.compose.yaml
  #- path: ocis.compose.yaml

networks:
  caddy:
    enable_ipv6: true
  caddy-glances:
  caddy-kubo:
  caddy-leanish:
  caddy-nextcloud:
  caddy-ollama:
  caddy-send:

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    env_file:
      - path: .env.caddy
      - path: .env.caddy.local
    networks:
      - caddy
      - caddy-glances
      - caddy-kubo
      - caddy-leanish
      - caddy-nextcloud
      - caddy-ollama
      - caddy-send
      - caddy-tandoor
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    user: 1000:1000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/log/caddy:/var/log/caddy
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy
      - nextcloud:/var/www/nextcloud:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  leanish:
    container_name: leanish
    image: natoboram/leanish
    depends_on:
      - caddy
    networks:
      - caddy-leanish
    restart: always

  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
