networks:
  caddy-collabora:
  caddy-kubo:
  caddy-leanish:
  caddy-nextcloud:
  caddy-send:
  nextcloud-collabora:
  nextcloud-ollama:
  nextcloud-postgres:
  nextcloud-redis:
  send-redis:

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - kubo
      - leanish
      - nextcloud
      - send
    env_file:
      - path: .env.caddy
        required: true
      - path: .env.caddy.local
        required: true
    networks:
      - caddy-collabora
      - caddy-kubo
      - caddy-leanish
      - caddy-nextcloud
      - caddy-send
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    user: 1000:1000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy
      - nextcloud:/var/www/nextcloud:ro

  clamav:
    container_name: clamav
    image: clamav/clamav:stable_base
    restart: always
    volumes:
      - clamav-lib:/var/lib/clamav
      - clamav-run:/tmp

  collabora:
    cap_add:
      - MKNOD
    container_name: collabora
    env_file:
      - path: .env.collabora
        required: true
      - path: .env.collabora.local
        required: true
    environment:
      - aliasgroup1=https://nextcloud.natoboram.duckdns.org:443
      - dictionaries=fr_CA en_CA
      - domain=nextcloud.natoboram.duckdns.org
      - server_name=collabora.natoboram.duckdns.org
      - TZ=America/Toronto
    image: collabora/code
    networks:
      - caddy-collabora
      - nextcloud-collabora
    restart: always

  kubo:
    container_name: kubo
    hostname: helion
    image: ipfs/kubo
    networks:
      - caddy-kubo
    ports:
      - 127.0.0.1:5001:5001
      - 4001:4001/tcp
      - 4001:4001/udp
      - 8080:8080
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  leanish:
    container_name: leanish
    image: natoboram/leanish
    networks:
      - caddy-leanish
    restart: always

  nextcloud:
    container_name: nextcloud
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: all
              driver: nvidia
    depends_on:
      - clamav
      - collabora
      - nextcloud-postgres
      - nextcloud-redis
      - ollama
    env_file:
      - path: .env.nextcloud
        required: true
      - path: .env.nextcloud.local
        required: true
    environment:
      - NC_ALLOW_LOCAL_REMOTE_SERVERS=true

      - POSTGRES_HOST=nextcloud-postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

      - REDIS_HOST=nextcloud-redis

      - SMTP_HOST=smtp.gmail.com
      - SMTP_SECURE=ssl
      - SMTP_PORT=465

      - TZ=America/Toronto
    image: nextcloud:fpm
    networks:
      - caddy-nextcloud
      - nextcloud-collabora
      - nextcloud-ollama
      - nextcloud-postgres
      - nextcloud-redis
    restart: always
    volumes:
      - /var/log/nextcloud.log:/var/www/html/data/nextcloud.log
      - clamav-run:/var/run/clamav:ro
      - nextcloud:/var/www/html

  nextcloud-cron:
    container_name: nextcloud-cron
    depends_on:
      - nextcloud
    entrypoint: /cron.sh
    extends: nextcloud
    networks:
      - nextcloud-collabora
      - nextcloud-ollama
      - nextcloud-postgres
      - nextcloud-redis

  nextcloud-postgres:
    container_name: nextcloud-postgres
    env_file:
      - path: .env.nextcloud-postgres
        required: true
      - path: .env.nextcloud-postgres.local
        required: true
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    image: postgres
    networks:
      - nextcloud-postgres
    restart: always
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    networks:
      - nextcloud-redis
    restart: always
    volumes:
      - nextcloud-redis:/data

  ollama:
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: all
              driver: nvidia
    image: ollama/ollama
    networks:
      - nextcloud-ollama
    ports:
      - 11434:11434
    restart: always
    volumes:
      - ollama:/root/.ollama

  send:
    container_name: send
    depends_on:
      - send-redis
    environment:
      - BASE_URL=https://send.natoboram.duckdns.org
      - REDIS_HOST=redis
    image: registry.gitlab.com/timvisee/send
    networks:
      - caddy-send
      - send-redis
    restart: always

  send-redis:
    container_name: send-redis
    image: redis:alpine
    networks:
      - send-redis
    restart: always
    volumes:
      - send-redis:/data

  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

volumes:
  clamav-lib:
  clamav-run:
  nextcloud:
  nextcloud-postgres:
  nextcloud-redis:
  ollama:
  send-redis:
