networks:
  caddy-kubo:
  caddy-leanish:
  caddy-nextcloud:
  caddy-send:
  nextcloud-localai:
  nextcloud-postgres:
  nextcloud-redis:
  send-redis:

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - kubo
      - leanish
      - nextcloud
      - send
    env_file:
      - path: .env.caddy
        required: true
      - path: .env.caddy.local
        required: true
    networks:
      - caddy-kubo
      - caddy-leanish
      - caddy-nextcloud
      - caddy-send
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    user: 1000:1000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy
      - nextcloud:/var/www/nextcloud:ro

  clamav:
    container_name: clamav
    image: clamav/clamav:stable_base
    volumes:
      - clamav-lib:/var/lib/clamav
      - clamav-run:/tmp
    restart: always

  kubo:
    container_name: kubo
    hostname: helion
    image: ipfs/kubo
    networks:
      - caddy-kubo
    ports:
      - 127.0.0.1:5001:5001
      - 4001:4001/tcp
      - 4001:4001/udp
      - 8080:8080
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  leanish:
    container_name: leanish
    image: natoboram/leanish
    networks:
      - caddy-leanish
    restart: always

  localai:
    container_name: localai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      interval: 1m
      retries: 5
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      timeout: 20m
    image: localai/localai:latest-aio-gpu-nvidia-cuda-11
    networks:
      - nextcloud-localai
    ports:
      - 11434:8080
    restart: always
    volumes:
      - localai:/build/models

  nextcloud:
    container_name: nextcloud
    depends_on:
      - clamav
      - localai
      - nextcloud-postgres
      - nextcloud-redis
    image: nextcloud:fpm
    networks:
      - caddy-nextcloud
      - nextcloud-localai
      - nextcloud-postgres
      - nextcloud-redis
    restart: always
    volumes:
      - /var/log/nextcloud.log:/var/www/html/data/nextcloud.log
      - clamav-run:/var/run/clamav:ro
      - nextcloud:/var/www/html
    environment:
      - NC_ALLOW_LOCAL_REMOTE_SERVERS=true

      - POSTGRES_HOST=nextcloud-postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

      - REDIS_HOST=nextcloud-redis

      - TZ=America/Toronto

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    networks:
      - nextcloud-redis
    restart: always
    volumes:
      - nextcloud-redis:/data

  nextcloud-postgres:
    container_name: nextcloud-postgres
    env_file:
      - path: .env.nextcloud-postgres
        required: true
      - path: .env.nextcloud-postgres.local
        required: true
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    image: postgres
    networks:
      - nextcloud-postgres
    restart: always
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data

  send:
    container_name: send
    depends_on:
      - send-redis
    environment:
      - BASE_URL=https://send.natoboram.duckdns.org
      - REDIS_HOST=redis
    image: registry.gitlab.com/timvisee/send
    networks:
      - caddy-send
      - send-redis
    restart: always

  send-redis:
    container_name: send-redis
    image: redis:alpine
    networks:
      - send-redis
    restart: always
    volumes:
      - send-redis:/data

  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

volumes:
  clamav-lib:
  clamav-run:
  localai:
  nextcloud:
  nextcloud-postgres:
  nextcloud-redis:
  send-redis:
