version: "3"

services:
  syncthing:
    container_name: syncthing
    hostname: helion
    image: syncthing/syncthing
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

  ipfs:
    container_name: ipfs
    hostname: helion
    image: ipfs/kubo
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/.ipfs:/data/ipfs
