version: "3"

services:
  syncthing:
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    hostname: helion
    image: syncthing/syncthing
    network_mode: host
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

  ipfs:
    container_name: ipfs
    hostname: helion
    image: ipfs/kubo
    network_mode: host
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  caddy:
    container_name: caddy
    depends_on:
      - ipfs
    image: caddy
    network_mode: host
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy
