services:
  syncthing:
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    hostname: helion
    image: syncthing/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: always
    user: 1000:1000
    volumes:
      - ~/.config/syncthing:/var/syncthing/config
      - ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher:/var/syncthing/PrismLauncher

      - ~/Desktop:/var/syncthing/Desktop
      - ~/Documents:/var/syncthing/Documents
      - ~/Downloads:/var/syncthing/Downloads
      - ~/Minecraft:/var/syncthing/Minecraft
      - ~/Music:/var/syncthing/Music
      - ~/Pictures:/var/syncthing/Pictures
      - ~/Sync:/var/syncthing/Sync
      - ~/Templates:/var/syncthing/Templates
      - ~/Videos:/var/syncthing/Videos

  ipfs:
    container_name: ipfs
    hostname: helion
    image: ipfs/kubo
    ports:
      - 4001:4001/tcp # ipfs swarm
      - 4001:4001/udp # ipfs swarm
      - 127.0.0.1:5001:5001 # ipfs api
      - 8080:8080 # ipfs gateway
    restart: always
    user: 1000:1000
    volumes:
      - ~/.ipfs:/data/ipfs

  caddy:
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - ipfs
      - send
    image: caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/config/caddy
      - ~/.local/share/caddy:/data/caddy

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - send-redis:/data

  send:
    container_name: send
    depends_on:
      - redis
    environment:
      - BASE_URL=https://natoboram-send.duckdns.org
      - REDIS_HOST=redis
    image: registry.gitlab.com/timvisee/send:latest
    ports:
      - 1443:1443
    restart: always

volumes:
  send-redis:
