version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: helion
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/.config/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    hostname: helion
    volumes:
      - ~/.ipfs:/data/ipfs
    network_mode: host
    restart: unless-stopped
