services:
  metube:
    container_name: metube
    depends_on:
      - authentik-server
    environment:
      - YTDL_OPTIONS_FILE=/yt-dlp.json
    image: ghcr.io/alexta69/metube
    networks:
      - authentik-metube
    restart: always
    volumes:
      - metube:/downloads
      - ./metube/yt-dlp.json:/yt-dlp.json:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  metube:
