services:
  metube:
    container_name: metube
    depends_on:
      - caddy
    environment:
      - YTDL_OPTIONS_FILE=/yt-dlp.json
    image: ghcr.io/alexta69/metube
    networks:
      - caddy-metube
    restart: always
    volumes:
      - metube:/downloads
      - ./metube/yt-dlp.json:/yt-dlp.json:ro

volumes:
  metube:
