# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets:
          - caddy:2019

  - job_name: collabora
    basic_auth:
      username: "%{COLLABORA_USERNAME}"
      password: "%{COLLABORA_PASSWORD}"
    metrics_path: /cool/getMetrics
    scheme: https
    static_configs:
      - targets:
          - collabora:9980
    tls_config:
      insecure_skip_verify: true

  - job_name: victoria-metrics
    static_configs:
      - targets:
          - victoria-metrics:8428

  - job_name: vmagent
    static_configs:
      - targets:
          - vmagent:8429
