services:
  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      - authentik-server
    image: louislam/uptime-kuma
    networks:
      - authentik-uptime-kuma
    # ports:
    #   - 3001:3001
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - uptime-kuma:/app/data

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  uptime-kuma:
