# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema.json
default: true
line-length: false
no-duplicate-heading:
  siblings_only: true
no-hard-tabs:
  code_blocks: false
  spaces_per_tab: 2
no-inline-html: false
