networks:
  authentik-dozzle:
  authentik-forgejo:
  authentik-glances:
  authentik-goaccess:
  authentik-metube:
  authentik-myspeed:
  authentik-postgres:
  authentik-qbittorrent:
  authentik-stirling-pdf:
  authentik-syncthing:
  authentik-uptime-kuma:

services:
  authentik-server:
    command: server
    container_name: authentik-server
    depends_on:
      authentik-postgres:
        condition: service_healthy
      caddy:
        condition: service_started
    env_file:
      - .env.authentik-server
      - .env.authentik-server.local
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
    image: ghcr.io/goauthentik/server:2025.10
    networks:
      - authentik-dozzle
      - authentik-forgejo
      - authentik-glances
      - authentik-goaccess
      - authentik-metube
      - authentik-myspeed
      - authentik-postgres
      - authentik-qbittorrent
      - authentik-stirling-pdf
      - authentik-syncthing
      - authentik-uptime-kuma
      - caddy-authentik
    # ports:
    #   - 9000:9000
    #   - 9443:9443
    restart: always
    volumes:
      - ./volumes/templates:/templates
      - authentik-media:/media

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  authentik-worker:
    command: worker
    container_name: authentik-worker
    depends_on:
      authentik-postgres:
        condition: service_healthy
    env_file:
      - .env.authentik-worker
      - .env.authentik-worker.local
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
    image: ghcr.io/goauthentik/server:2025.10
    networks:
      - authentik-postgres
    # ports:
    #   - 9000:9000
    #   - 9443:9443
    restart: always
    volumes:
      - ./volumes/certs:/certs
      - ./volumes/templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - authentik-media:/media

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  authentik-postgres:
    container_name: authentik-postgres
    env_file:
      - .env.authentik-postgres
      - .env.authentik-postgres.local
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: postgres:18-alpine
    networks:
      - authentik-postgres
      - uptime-kuma-authentik-postgres
    restart: always
    volumes:
      - authentik-postgres:/var/lib/postgresql

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  authentik-media:
  authentik-postgres:
