networks:
  authentik-dozzle:
  authentik-glances:
  authentik-goaccess:
  authentik-metube:
  authentik-myspeed:
  authentik-postgres:
  authentik-qbittorrent:
  authentik-redis:
  authentik-stirling-pdf:
  authentik-syncthing:
  authentik-uptime-kuma:

services:
  authentik-server:
    command: server
    container_name: authentik-server
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
      caddy:
        condition: service_started
    env_file:
      - .env.authentik-server
      - .env.authentik-server.local
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
    image: ghcr.io/goauthentik/server
    networks:
      - authentik-dozzle
      - authentik-glances
      - authentik-goaccess
      - authentik-metube
      - authentik-myspeed
      - authentik-postgres
      - authentik-qbittorrent
      - authentik-redis
      - authentik-stirling-pdf
      - authentik-syncthing
      - authentik-uptime-kuma
      - caddy-authentik
    # ports:
    #   - 9000:9000
    #   - 9443:9443
    restart: always
    volumes:
      - ./authentik/templates:/templates
      - authentik-media:/media

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  authentik-worker:
    command: worker
    container_name: authentik-worker
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    env_file:
      - .env.authentik-worker
      - .env.authentik-worker.local
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
    image: ghcr.io/goauthentik/server
    networks:
      - authentik-postgres
      - authentik-redis
    # ports:
    #   - 9000:9000
    #   - 9443:9443
    restart: always
    volumes:
      - ./authentik/certs:/certs
      - ./authentik/templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - authentik-media:/media

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  authentik-postgres:
    container_name: authentik-postgres
    env_file:
      - .env.authentik-postgres
      - .env.authentik-postgres.local
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:18-alpine
    networks:
      - authentik-postgres
      - uptime-kuma-authentik-postgres
    restart: always
    volumes:
      - authentik-postgres:/var/lib/postgresql/data

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  authentik-redis:
    command: --save 60 1 --loglevel warning
    container_name: authentik-redis
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
    image: docker.io/library/redis:alpine
    networks:
      - authentik-redis
      - uptime-kuma-authentik-redis
    restart: always
    volumes:
      - authentik-redis:/data

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  authentik-media:
  authentik-postgres:
  authentik-redis:
