networks:
  caddy:
    enable_ipv6: true
  caddy-anubis:
  caddy-authentik:
  caddy-beszel:
  caddy-dozzle:
  caddy-glances:
  caddy-goaccess:
  caddy-jellyfin:
  caddy-kubo:
  caddy-leanish:
  caddy-metube:
  caddy-myspeed:
  caddy-nextcloud:
  caddy-ollama:
  caddy-qbittorrent:
  caddy-send:
  caddy-stirling-pdf:
  caddy-syncthing:
  caddy-uptime-kuma:
  caddy-vikunja:

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: caddy
    depends_on:
      - geoipupdate
    env_file:
      - path: .env.caddy
      - path: .env.caddy.local
    networks:
      - caddy
      - caddy-anubis
      - caddy-authentik
      - caddy-beszel
      - caddy-dozzle
      - caddy-glances
      - caddy-goaccess
      - caddy-jellyfin
      - caddy-kubo
      - caddy-leanish
      - caddy-metube
      - caddy-myspeed
      - caddy-nextcloud
      - caddy-ollama
      - caddy-qbittorrent
      - caddy-send
      - caddy-stirling-pdf
      - caddy-syncthing
      - caddy-uptime-kuma
      - caddy-vikunja
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: always
    volumes:
      - ./caddy:/var/www/html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/log/caddy:/var/log/caddy
      - caddy-config:/config/caddy
      - caddy-data:/data/caddy
      - geoipupdate:/data/geoip:ro
      - goaccess-report:/var/www/goaccess:ro
      - nextcloud:/var/www/nextcloud:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  caddy-config:
  caddy-data:
