include:
  - path: authelia.compose.yaml
  - path: authentik.compose.yaml
  - path: beszel.compose.yaml
  - path: caddy.compose.yaml
  - path: dozzle.compose.yaml
  - path: glances.compose.yaml
  - path: goaccess.compose.yaml
  - path: jellyfin.compose.yaml
  - path: kubo.compose.yaml
  - path: leanish.compose.yaml
  - path: metube.compose.yaml
  - path: myspeed.compose.yaml
  - path: nextcloud.compose.yaml
  - path: ollama.compose.yaml
  - path: qbittorrent.compose.yaml
  - path: send.compose.yaml
  - path: syncthing.compose.yaml
  - path: uptime-kuma.compose.yaml
  - path: watchtower.compose.yaml
