secrets:
  GEOIPUPDATE_ACCOUNT_ID:
    file: ./geoipupdate/secrets/GEOIPUPDATE_ACCOUNT_ID
  GEOIPUPDATE_LICENSE_KEY:
    file: ./geoipupdate/secrets/GEOIPUPDATE_LICENSE_KEY

services:
  geoipupdate:
    container_name: geoipupdate
    environment:
      GEOIPUPDATE_ACCOUNT_ID_FILE: /run/secrets/GEOIPUPDATE_ACCOUNT_ID
      GEOIPUPDATE_EDITION_IDS: GeoLite2-ASN GeoLite2-City GeoLite2-Country
      GEOIPUPDATE_FREQUENCY: 72
      GEOIPUPDATE_LICENSE_KEY_FILE: /run/secrets/GEOIPUPDATE_LICENSE_KEY
    image: ghcr.io/maxmind/geoipupdate
    restart: always
    secrets:
      - GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY
    volumes:
      - geoipupdate:/usr/share/GeoIP

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  geoipupdate:
