services:
  goaccess:
    # This attribute has to be overridden in `compose.override.yaml`.
    command:
      - /srv/logs/caddy/$$DOMAIN.log
      - --log-format=CADDY
      - --no-global-config
      - --output=/srv/report/index.html
      - --real-time-html
      - --tz=America/Toronto
      - --ws-url=wss://goaccess.$$DOMAIN:443
    container_name: goaccess
    depends_on:
      - authentik-server
      - caddy
    image: allinurl/goaccess
    networks:
      - authentik-goaccess
      - caddy-goaccess
    restart: always
    volumes:
      - ./goaccess:/srv/config:ro
      - /var/log/caddy:/srv/logs/caddy:ro
      - goaccess:/srv/report

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  goaccess:
