services:
  ollama:
    container_name: ollama
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    image: ollama/ollama
    networks:
      - caddy-ollama
      - nextcloud-ollama
    ports:
      - 11434:11434
    restart: always
    volumes:
      - ollama:/root/.ollama

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  ollama:
