services:
  ollama:
    container_name: ollama
    devices:
      - /dev/dri
      - /dev/kfd
    env_file:
      - .env.ollama
      - .env.ollama.local
    image: ollama/ollama:rocm
    networks:
      - caddy-ollama
      - nextcloud-ollama
    ports:
      - 11434:11434
    restart: always
    volumes:
      - ollama:/root/.ollama

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  ollama:
