services:
  syncthing:
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
    hostname: phantom
    image: syncthing/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always
    volumes:
      - syncthing:/var/syncthing
      - syncthing-jellyfin:/var/syncthing/Jellyfin

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  syncthing-jellyfin:
  syncthing:
