{
 "title": "Collabora",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(loolwsd_count, instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Counters $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Active View - Active  Docs",
   "type": "stat",
   "description": "Currently opened documents",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "document_active_views_active_count_total{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total views of all docs ",
   "type": "stat",
   "description": "Total number of views (active or expired) of all documents (active and expired)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "document_all_views_all_count_total{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All views",
   "type": "stat",
   "description": "Total number of views (active or expired) of all documents (active and expired).",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "document_all_views_all_count_total{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "All Expired",
   "type": "stat",
   "description": "Total number of all views (active or expired) of expired documents",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "document_expired_views_all_count_total{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Expired - Active",
   "type": "stat",
   "description": "Total number of expired views of all active documents",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "document_active_views_expired_count_total{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Bytes received (Since Restart)",
   "type": "stat",
   "description": "Total number of bytes received from clients by all documents (active or expired)",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "document_all_received_from_client_total_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes sent (Since Restart)",
   "type": "stat",
   "description": "Total number of bytes sent to clients by all documents (active or expired)",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "document_all_sent_to_clients_total_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Processes $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "instance" },
  {
   "title": "loolwsd processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loolwsd_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "loolwsd threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loolwsd_thread_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "forkit processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forkit_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "forkit threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forkit_thread_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "kit processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kit_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "kit assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kit_assigned_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "kit unaassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kit_unassigned_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "kit threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kit_thread_count_total{instance=~'$instance'}"
    }
   ]
  },
  { "title": "Stats $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Active Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "document_active_views_active_count_total{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(document_all_view_load_duration_total_milliseconds{instance=~'$instance'}[1m])/1000",
     "legendFormat": "All {{instance}}"
    },
    {
     "expr": "rate(document_active_view_load_duration_total_milliseconds{instance=~'$instance'}[1m])/1000",
     "legendFormat": "Active {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(loolwsd_cpu_time_seconds{instance=~\"$instance\"}[3m])",
     "legendFormat": "loolwsd cpu {{instance}}"
    },
    {
     "expr": "rate(forkit_cpu_time_seconds{instance=~\"$instance\"}[3m])",
     "legendFormat": "forkit cpu {{instance}}"
    },
    {
     "expr": "rate(kit_cpu_time_total_seconds{instance=~\"$instance\"}[3m])",
     "legendFormat": "kit cpu {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "loolwsd_memory_used_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "loolwsd {{instance}}"
    },
    {
     "expr": "forkit_memory_used_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "forkit {{instance}}"
    },
    {
     "expr": "kit_memory_used_total_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "kit {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "global_memory_free_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "loolwsd memory {{instance}}"
    },
    {
     "expr": "forkit_memory_used_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "forkit memory {{instance}}"
    },
    {
     "expr": "kit_memory_used_total_bytes{instance=~'$instance'}/1048576",
     "legendFormat": "kit memory {{instance}}"
    }
   ]
  },
  {
   "title": "Byte sent to client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(document_all_sent_to_clients_total_bytes{instance=~\"$instance\"}[1m])/1048576",
     "legendFormat": "All {{instance}}"
    },
    {
     "expr": "rate(document_active_sent_to_clients_total_bytes{instance=~\"$instance\"}[1m])/1048576",
     "legendFormat": "Active {{instance}}"
    },
    {
     "expr": "rate(document_expired_sent_to_clients_total_bytes{instance=~\"$instance\"}[1m])/1048576",
     "legendFormat": "Expired {{instance}}"
    }
   ]
  },
  {
   "title": "Byte received from client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(document_all_received_from_client_total_bytes{instance=~\"$instance\"}[1m])/1048576",
     "legendFormat": "All {{instance}}"
    }
   ]
  }
 ]
}