services:
  beszel:
    container_name: beszel
    depends_on:
      - authentik-server
      - caddy
    env_file:
      - .env.beszel
      - .env.beszel.local
    extra_hosts:
      - host.docker.internal:host-gateway
    image: henrygd/beszel
    networks:
      - caddy-beszel
    restart: always
    volumes:
      - beszel:/beszel_data

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  beszel-agent:
    container_name: beszel-agent
    depends_on:
      - beszel
    env_file:
      - .env.beszel-agent
      - .env.beszel-agent.local
    image: henrygd/beszel-agent
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  beszel:
