services:
  watchtower:
    container_name: watchtower
    environment:
      WATCHTOWER_CLEANUP: true
    image: nickfedor/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
