secrets:
  # Sets `log-file` and `ws-url`.
  conf:
    file: ./secrets/goaccess.conf

services:
  goaccess:
    command:
      - --agent-list
      - --config-file=/srv/config/goaccess.conf
      - --db-path=/srv/db
      - --external-assets
      - --geoip-database=/srv/mmdb/GeoLite2-ASN.mmdb
      - --geoip-database=/srv/mmdb/GeoLite2-City.mmdb
      - --geoip-database=/srv/mmdb/GeoLite2-Country.mmdb
      - --jobs=6
      - --keep-last=90
      - --log-format=CADDY
      - --no-global-config
      - --no-query-string
      - --output=/srv/report/index.html
      - --persist
      - --real-time-html
      - --restore
      - --tz=America/Toronto
    container_name: goaccess
    depends_on:
      - authentik-server
      - caddy
      - geoipupdate
    image: allinurl/goaccess
    networks:
      - authentik-goaccess
      - caddy-goaccess
    restart: always
    secrets:
      - source: conf
        target: /srv/config/goaccess.conf
    volumes:
      - /var/log/caddy:/srv/logs/caddy:ro
      - geoipupdate:/srv/mmdb:ro
      - goaccess-db:/srv/db
      - goaccess-report:/srv/report

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  goaccess-db:
  goaccess-report:
