name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: phantom
    runs-on: ubuntu-latest

    steps:
      - run: "curl --oauth2-bearer '${{secrets.WATCHTOWER_HTTP_API_TOKEN}}' --tlsv1.3 'https://watchtower.${{secrets.DOMAIN}}/v1/update'"
